language: node_js
node_js:
  - 10
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
script:
  - npm run ci
deploy:
  provider: heroku
  api_key:
    secure: c767792c-91c3-4ed8-b409-eac567238069
  app: messaging-app-client
